#!/usr/bin/python3
"""Task-6"""
def raise_exception_msg(message=""):
    raise NameError(message)
"""End"""
